package com.antiam.web;

import com.antiam.domain.ApplicationProtocol;
import com.antiam.domain.IdentitySourceType;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import java.util.Map;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1/catalog")
@Tag(name = "功能目录", description = "系统能力、协议类型和身份源类型发现接口")
public class CatalogController {

    /**
     * 返回当前系统声明支持的功能模块和枚举类型。
     */
    @Operation(summary = "查询功能目录", description = "返回应用协议、身份源类型和当前 IAM 后端支持的功能模块清单。")
    @GetMapping
    Map<String, Object> catalog() {
        return Map.of(
            "applicationProtocols", ApplicationProtocol.values(),
            "identitySourceTypes", IdentitySourceType.values(),
            "modules", new String[] {
                "organization-directory",
                "organization-profile",
                "organization-tree",
                "organization-user-list",
                "users-and-groups",
                "user-directory-search",
                "user-profile",
                "rbac",
                "access-resource-profile",
                "access-resource-update",
                "access-resource-search",
                "user-effective-access",
                "group-membership-list",
                "group-effective-access",
                "permission-impact-analysis",
                "role-impact-analysis",
                "application-sso",
                "application-role-binding",
                "application-role-access",
                "application-assignment",
                "application-assignment-lifecycle",
                "application-assignment-expiry",
                "application-access-decision",
                "user-application-portal",
                "self-service-application-portal",
                "self-service-requestable-application",
                "application-access-request",
                "self-service-application-access-request",
                "application-access-approval",
                "application-access-review",
                "user-deprovisioning-access-revoke",
                "user-deprovisioning-session-revoke",
                "user-deprovisioning-oauth-token-revoke",
                "authentication-session",
                "authentication-session-filter",
                "authentication-session-history",
                "authentication-session-force-logout",
                "authentication-event",
                "authentication-event-search",
                "logout-event",
                "login-risk-event",
                "oauth2-authorization-code",
                "oauth2-pkce",
                "oauth2-refresh-token",
                "oauth2-token-inventory",
                "oauth2-token-profile",
                "oauth2-token-introspection",
                "oauth2-token-revocation",
                "oauth2-token-admin-revocation",
                "oauth2-consent",
                "oauth2-consent-search",
                "oauth2-consent-profile",
                "oauth2-consent-revocation",
                "oidc-discovery",
                "oidc-userinfo",
                "oidc-jwks",
                "oidc-rs256-id-token",
                "oidc-claim-policy",
                "saml2-metadata",
                "saml2-metadata-xml",
                "saml2-assertion",
                "saml2-response-xml",
                "cas-service-ticket",
                "cas-service-validate-xml",
                "identity-source",
                "identity-source-profile",
                "identity-source-search",
                "identity-source-update",
                "identity-source-lifecycle",
                "identity-source-connector",
                "identity-source-connector-lifecycle",
                "identity-sync-job",
                "identity-sync-job-profile",
                "identity-sync-job-update",
                "identity-sync-job-lifecycle",
                "identity-sync-run",
                "identity-sync-run-profile",
                "scim2-users",
                "scim2-groups",
                "scim2-organizations",
                "scim2-resource-profile",
                "scim2-filtering",
                "scim2-pagination",
                "scim2-discovery",
                "openapi-documentation",
                "authentication-policy",
                "authentication-policy-lifecycle",
                "authentication-policy-evaluation",
                "authentication-policy-actions",
                "password-policy-enforcement",
                "password-failure-lockout",
                "password-expiry-policy",
                "password-history-policy",
                "password-reset-ticket",
                "password-reset-ticket-search",
                "password-reset-ticket-profile",
                "password-reset-ticket-revocation",
                "self-service-password-change",
                "risk-rule",
                "risk-rule-profile",
                "risk-rule-search",
                "risk-rule-update",
                "risk-rule-lifecycle",
                "risk-assessment",
                "risk-assessment-profile",
                "risk-assessment-search",
                "risk-device-fingerprint",
                "risk-geo-location",
                "dashboard-summary",
                "dashboard-metrics",
                "system-setting",
                "system-setting-search",
                "system-setting-deletion",
                "jwt-signing-key",
                "jwt-signing-key-search",
                "jwt-signing-key-profile",
                "jwt-signing-key-retirement-guard",
                "tenant",
                "tenant-setting",
                "tenant-setting-profile",
                "tenant-setting-search",
                "tenant-setting-deletion",
                "mfa",
                "mfa-factor-profile",
                "mfa-factor-update",
                "mfa-factor-lifecycle",
                "mfa-challenge",
                "mfa-challenge-search",
                "mfa-challenge-profile",
                "mfa-recovery-code",
                "audit-event-profile",
                "audit-event-keyword-search",
                "audit"
            });
    }
}
