spring:
  application:
    name: iam
  datasource:
    url: ${IAM_DATASOURCE_URL:jdbc:postgresql://localhost:5432/js_iam}
    username: ${IAM_DATASOURCE_USERNAME:js_iam}
    password: ${IAM_DATASOURCE_PASSWORD:js_iam}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  threads:
    virtual:
      enabled: true
server:
  port: ${IAM_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

iam:
  geoip:
    database-path: ${IAM_GEOIP_DATABASE_PATH:}

sms:
  config-type: yaml
  blends:
    fixed-code:
      supplier: fixed-code
      factory: com.antiam.sms.fixed.FixedCodeSmsFactory
      code: ${IAM_SMS_FIXED_CODE:666666}
