spring:
  application:
    name: ant-iam
  datasource:
    url: ${ANT_IAM_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ant_iam}
    username: ${ANT_IAM_DATASOURCE_USERNAME:ant_iam}
    password: ${ANT_IAM_DATASOURCE_PASSWORD:ant_iam}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
  threads:
    virtual:
      enabled: true
server:
  port: ${ANT_IAM_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

ant-iam:
  geoip:
    database-path: ${ANT_IAM_GEOIP_DATABASE_PATH:}

sms:
  blends:
    fixed-code:
      supplier: fixed-code
      code: ${ANT_IAM_SMS_FIXED_CODE:666666}
